[package]
name = "samuelbg04/family-tree"
version = "0.1.2"
description = "A PHP-based family tree web application"

[dependencies]
"php/php-32" = "=8.3.2101-rc.1"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php-32:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--port", "8000", "--root", "/app"]
